[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "mazegen"
version = "1.0.0"
description = "Reusable maze generator module"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "build>=1.2.2.post1",
    "strenum>=0.4.15",
]

[project.scripts]
a-maze-ing = "a_maze_ing:main"

[tool.setuptools]
py-modules = ["mazegen", "a_maze_ing"]

[tool.setuptools.packages.find]
where = ["."]
include = ["srcs*"]
